/** Design tokens ported 1:1 from the Stitch "Persona AI — Modern Archive" project
 *  (stitch.withgoogle.com project 12011515695823926206). Monochrome editorial system:
 *  Source Serif 4 for display/headlines, Inter for body/labels, black primary on cream. */
const path = require("path");

module.exports = {
  // Absolute so the glob works whether next runs from frontend/ or the repo root.
  content: [path.join(__dirname, "app/**/*.{js,jsx}")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1b1d",
        "surface-container-highest": "#e4e2e4",
        "inverse-surface": "#303032",
        "on-error-container": "#93000a",
        "surface-container-low": "#f6f3f5",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        tertiary: "#000000",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed-variant": "#574425",
        "primary-container": "#131b2e",
        "on-primary-container": "#7c839b",
        "primary-fixed-dim": "#bec6e0",
        secondary: "#5f5e5c",
        "on-background": "#1b1b1d",
        "tertiary-container": "#271901",
        "surface-tint": "#565e74",
        "on-secondary-container": "#636260",
        surface: "#fcf8fa",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#474745",
        "inverse-on-surface": "#f3f0f2",
        "on-primary-fixed": "#131b2e",
        "surface-variant": "#e4e2e4",
        background: "#fcf8fa",
        "on-secondary-fixed": "#1c1c1a",
        primary: "#000000",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#271901",
        "secondary-fixed-dim": "#c8c6c3",
        "surface-container-high": "#eae7e9",
        "on-surface-variant": "#45464d",
        "on-tertiary-container": "#98805d",
        "inverse-primary": "#bec6e0",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed": "#fcdeb5",
        "secondary-fixed": "#e5e2df",
        "tertiary-fixed-dim": "#dec29a",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9db",
        outline: "#76777d",
        "secondary-container": "#e2dfdc",
        "surface-container": "#f0edef",
        error: "#ba1a1a",
        "surface-bright": "#fcf8fa",
        stripe: "#635BFF",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "container-max": "1200px",
        gutter: "24px",
        unit: "8px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        serif: ['"Source Serif 4"', "Georgia", "serif"],
        "display-lg": ['"Source Serif 4"', "Georgia", "serif"],
        citation: ["Inter", "sans-serif"],
        "mono-label": ["Inter", "sans-serif"],
        "headline-sm": ['"Source Serif 4"', "Georgia", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ['"Source Serif 4"', "Georgia", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ['"Source Serif 4"', "Georgia", "serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        citation: ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "mono-label": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
